# Generated by Django 2.1.1 on 2018-11-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_persona', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
    ]
